// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7tDk6CKWPe1X77pv1vH48wftUb-1TmdY',
    appId: '1:447951543821:web:35f73f90b466792936ff44',
    messagingSenderId: '447951543821',
    projectId: 'tfm-admin-bf396',
    authDomain: 'tfm-admin-bf396.firebaseapp.com',
    storageBucket: 'tfm-admin-bf396.appspot.com',
    measurementId: 'G-CQG9TB1M9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoDOofm70f5RyEqIAgIzdsxeHCmI7Ksao',
    appId: '1:447951543821:android:afb8130bb1070bcf36ff44',
    messagingSenderId: '447951543821',
    projectId: 'tfm-admin-bf396',
    storageBucket: 'tfm-admin-bf396.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_s_HI_ZDAvLBsR4PJ1HICMifIxRgsS4U',
    appId: '1:447951543821:ios:c8f2469285ed454e36ff44',
    messagingSenderId: '447951543821',
    projectId: 'tfm-admin-bf396',
    storageBucket: 'tfm-admin-bf396.appspot.com',
    androidClientId: '447951543821-bpam8gf1gkshe4t5d57lpi6h16rf777p.apps.googleusercontent.com',
    iosClientId: '447951543821-0dfufis5sii0qmiighecl0ck8s28b7ua.apps.googleusercontent.com',
    iosBundleId: 'com.example.tfmAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_s_HI_ZDAvLBsR4PJ1HICMifIxRgsS4U',
    appId: '1:447951543821:ios:c8f2469285ed454e36ff44',
    messagingSenderId: '447951543821',
    projectId: 'tfm-admin-bf396',
    storageBucket: 'tfm-admin-bf396.appspot.com',
    androidClientId: '447951543821-bpam8gf1gkshe4t5d57lpi6h16rf777p.apps.googleusercontent.com',
    iosClientId: '447951543821-0dfufis5sii0qmiighecl0ck8s28b7ua.apps.googleusercontent.com',
    iosBundleId: 'com.example.tfmAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7tDk6CKWPe1X77pv1vH48wftUb-1TmdY',
    appId: '1:447951543821:web:b16be8c63b5b016a36ff44',
    messagingSenderId: '447951543821',
    projectId: 'tfm-admin-bf396',
    authDomain: 'tfm-admin-bf396.firebaseapp.com',
    storageBucket: 'tfm-admin-bf396.appspot.com',
    measurementId: 'G-8ZGTKVQGLJ',
  );
}
